#!/bin/bash
#
getconfigdata()
{
if [ -f /var/tmp/results.$sub ]
then
	mv /var/tmp/results.$sub /var/tmp/results.$sub.prev
fi
az account set -s subscription id
az group list |grep name > /tmp/resgrplist
for i in `cat /tmp/resgrplist`
do 
	grpname=`echo $i|awk -F: '{print $NF}'|tr -d "\""|tr -d ","`
	if [ ! -z $grpname ]
	then
#	grpname="bala-test"
	echo "Resource group: $grpname" >> /var/tmp/results.$sub
	echo "---------------------------------------" >> /var/tmp/results.$sub
	az group deployment list --resource-group $grpname > /tmp/resgrpdata
#	grep resourceName /tmp/resgrpdata
	jq '.[].properties.dependencies[].dependsOn[]| select(.resourceType == "microsoft.insights/components")| .resourceName' /tmp/resgrpdata|uniq|tr -d "\"" > /tmp/resnamelist
	cat /tmp/resnamelist|while read line
	do
                echo "Resource name: $line" >> /var/tmp/results.$sub
		az webapp config appsettings list --resource-group $grpname --name $line >> /var/tmp/results.$sub
        done
	rm /tmp/resnamelist
	fi
done
}

cat subslist|while read sub
do
	echo "Running data collection for $sub ..."
	az account set -s $sub
	getconfigdata
	az tag list > /var/tmp/tag.$sub.json
	az appservice plan list > /var/tmp/ASElist.$sub
	if [ -f /var/tmp/results.$sub.prev ]
	then
		echo "Checking variation against previous data ..."
		echo "#############################################"
		diff /var/tmp/results.$sub.prev /var/tmp/results.$sub > /var/tmp/variation_$sub
	fi
done

